# Data augmentation

In [1]:
import pandas as pd

In [84]:
csv = pd.read_csv('/Users/martialchouvel/code/mchouvel/counting_cards/raw_data/n4/test/_annotations.csv')

In [85]:
csv

,Unnamed: 0,filename,width,height,class,xmin,ymin,xmax,ymax
0,0,7C13_jpg.rf.05ada657164eb4d74d8262a3cf62c973.jpg,416,416,7C,238,151,276,174
1,1,2C19_jpg.rf.0360b8c770eb7d2fe01db6c6ee7da721.jpg,416,416,2C,119,195,156,220
2,2,4D51_jpg.rf.121039ff923296cf4b0c75cc5ae9bcdc.jpg,416,416,4D,289,143,331,167
3,4,5H24_jpg.rf.0ec4605bb731c5c9f1c64b93e76476f4.jpg,416,416,5H,296,180,342,224
4,5,3H33_jpg.rf.101724b7cefcb13d822af5b0a75d59f9.jpg,416,416,3H,243,196,264,236
...,...,...,...,...,...,...,...,...,...
267,271,9C2_jpg.rf.ffe1a6cd252f5e294fd66b057e2f40df.jpg,416,416,9C,280,266,302,318
268,272,4D8_jpg.rf.fb0ad0af6cd9af4c53db9072d1574dc3.jpg,416,416,4D,297,141,357,159
269,273,3S43_jpg.rf.f9a870ed3efdf0a9d6654c24a8951c6e.jpg,416,416,3S,49,177,94,242
270,274,5H12_jpg.rf.eaa4186adfc459f470be8311d8466119.jpg,416,416,5H,268,238,317,275
271,275,2S12_jpg.rf.f1c3941eae135c9112403771e9e1f769.jpg,416,416,2S,0,58,24,126

In [86]:
to_drop = []
for index, row in csv.iterrows():
    if row["filename"][4] == 'R':
        to_drop.append(index)
csv = csv.drop(to_drop)

In [87]:
csv

,Unnamed: 0,filename,width,height,class,xmin,ymin,xmax,ymax
0,0,7C13_jpg.rf.05ada657164eb4d74d8262a3cf62c973.jpg,416,416,7C,238,151,276,174
1,1,2C19_jpg.rf.0360b8c770eb7d2fe01db6c6ee7da721.jpg,416,416,2C,119,195,156,220
2,2,4D51_jpg.rf.121039ff923296cf4b0c75cc5ae9bcdc.jpg,416,416,4D,289,143,331,167
3,4,5H24_jpg.rf.0ec4605bb731c5c9f1c64b93e76476f4.jpg,416,416,5H,296,180,342,224
4,5,3H33_jpg.rf.101724b7cefcb13d822af5b0a75d59f9.jpg,416,416,3H,243,196,264,236
...,...,...,...,...,...,...,...,...,...
267,271,9C2_jpg.rf.ffe1a6cd252f5e294fd66b057e2f40df.jpg,416,416,9C,280,266,302,318
268,272,4D8_jpg.rf.fb0ad0af6cd9af4c53db9072d1574dc3.jpg,416,416,4D,297,141,357,159
269,273,3S43_jpg.rf.f9a870ed3efdf0a9d6654c24a8951c6e.jpg,416,416,3S,49,177,94,242
270,274,5H12_jpg.rf.eaa4186adfc459f470be8311d8466119.jpg,416,416,5H,268,238,317,275
271,275,2S12_jpg.rf.f1c3941eae135c9112403771e9e1f769.jpg,416,416,2S,0,58,24,126

In [88]:
csv["class"] = csv["filename"].apply(lambda x: x[0:3] if x[0:2]=='10' else x[0:2])

In [89]:
csv

,Unnamed: 0,filename,width,height,class,xmin,ymin,xmax,ymax
0,0,7C13_jpg.rf.05ada657164eb4d74d8262a3cf62c973.jpg,416,416,7C,238,151,276,174
1,1,2C19_jpg.rf.0360b8c770eb7d2fe01db6c6ee7da721.jpg,416,416,2C,119,195,156,220
2,2,4D51_jpg.rf.121039ff923296cf4b0c75cc5ae9bcdc.jpg,416,416,4D,289,143,331,167
3,4,5H24_jpg.rf.0ec4605bb731c5c9f1c64b93e76476f4.jpg,416,416,5H,296,180,342,224
4,5,3H33_jpg.rf.101724b7cefcb13d822af5b0a75d59f9.jpg,416,416,3H,243,196,264,236
...,...,...,...,...,...,...,...,...,...
267,271,9C2_jpg.rf.ffe1a6cd252f5e294fd66b057e2f40df.jpg,416,416,9C,280,266,302,318
268,272,4D8_jpg.rf.fb0ad0af6cd9af4c53db9072d1574dc3.jpg,416,416,4D,297,141,357,159
269,273,3S43_jpg.rf.f9a870ed3efdf0a9d6654c24a8951c6e.jpg,416,416,3S,49,177,94,242
270,274,5H12_jpg.rf.eaa4186adfc459f470be8311d8466119.jpg,416,416,5H,268,238,317,275
271,275,2S12_jpg.rf.f1c3941eae135c9112403771e9e1f769.jpg,416,416,2S,0,58,24,126

In [90]:
csv.to_csv('/Users/martialchouvel/code/mchouvel/counting_cards/raw_data/n4/test/_annotations.csv', ',')

In [ ]:
python notebooks/martial/scripts/generate_tfrecord.py raw_data/n4/valid/_annotations.csv notebooks/martial/training_files/label_map.pbtxt raw_data/n4/valid/ raw_data/n4/valid-n3.record

In [92]:
import tensorflow as tf

In [96]:
prefix = '/Users/martialchouvel/code/mchouvel/counting_cards/notebooks/martial'
# Create dataset from multiple .tfrecord files
list_of_tfrecord_files = [prefix + "/training_files/valid0.record", prefix + "/training_files/valid3.record"]
dataset = tf.data.TFRecordDataset(list_of_tfrecord_files)

# Save dataset to .tfrecord file
filename = prefix + '/training_files/valid.record'
writer = tf.data.experimental.TFRecordWriter(filename)
writer.write(dataset)

In [ ]:
python models/research/object_detection/export_inference_graph.py --input_type image_tensor --pipeline_config_path notebooks/martial/models/ssd_mobilenet_v2/pipeline.config --trained_checkpoint_prefix notebooks/martial/training_output/ckpt-9 --output_directory notebooks/martial/training_outputinference_graph